name: 🐛 Bug Report
description: Reporta un error o comportament inesperat
title: "[BUG] Descripció breu"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripció
      description: Explica quin és el problema
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos per reproduir
      description: Explica com es pot reproduir el bug
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Resultat esperat
      placeholder: "..."
  - type: input
    id: environment
    attributes:
      label: Entorn
      placeholder: "OS, navegador, versió, etc."